version: '3'
services:
  pusher:
    build: .
    restart: always
    ports:
      - 9000:9000
    command: ["./pusher"]
  nats-streaming:
    image: nats-streaming:0.18.0
    container_name: "nats-streaming"
    ports:
      - 4222:4222
      - 8222:8222
